# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

"""
setup.py for ovui

Builds the native shared libraries and pybind11 module via CMake, then packages
them into a wheel alongside the Python sources and resource files (fonts, glyphs).

Usage:
    pip install .
    pip install -e .          # editable / development install
    python -m build           # build wheel
"""

import os
import platform
import shlex
import shutil
import subprocess
import sys
import sysconfig
from pathlib import Path
from typing import Optional

from setuptools import Extension, setup
from setuptools.command.build_ext import build_ext

IS_WINDOWS = platform.system() == "Windows"
IS_MACOS = platform.system() == "Darwin"
REPO_ROOT = Path(__file__).resolve().parent.parent
VERSION_FILE = REPO_ROOT / "VERSION.md"
BUILD_INFO_PATH = Path(__file__).resolve().parent / "python" / "omni" / "ui" / "_build_info.py"


def _read_project_version() -> str:
    version = VERSION_FILE.read_text(encoding="utf-8").strip()
    if not version:
        raise RuntimeError(f"{VERSION_FILE} is empty")
    return version


def _read_commit_sha() -> str:
    """Resolve the source commit SHA of the build.

    Resolution order (first non-empty wins):
      1. OVUI_BUILD_COMMIT_SHA — explicit override (set by CI for reproducibility)
      2. GITHUB_SHA — auto-set by GitHub Actions
      3. CI_COMMIT_SHA — auto-set by GitLab CI
      4. `git rev-parse HEAD` from REPO_ROOT — local builds
      5. "unknown"
    """
    for env_var in ("OVUI_BUILD_COMMIT_SHA", "GITHUB_SHA", "CI_COMMIT_SHA"):
        value = os.environ.get(env_var, "").strip()
        if value:
            return value
    try:
        result = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=False,
            timeout=10,
        )
        if result.returncode == 0:
            sha = result.stdout.strip()
            if sha:
                return sha
    except (OSError, subprocess.SubprocessError):
        pass
    return "unknown"


def _qualified_version(base_version: str, commit: str) -> str:
    """Build a PEP 440-compliant version that bakes the short commit SHA into
    the wheel filename.

    PEP 427 wheel filenames are `{name}-{version}(-{build})?-{py}-{abi}-{plat}`,
    so the SHA has to ride along inside the version field. PEP 440 local-version
    identifiers (the `+local` suffix) are the right slot: they survive into the
    wheel filename verbatim and `pip` installs them like any other version.
    The `g` prefix mirrors the `setuptools-scm` / `git describe` convention.
    """
    if not commit or commit == "unknown" or len(commit) < 7:
        return base_version
    return f"{base_version}+g{commit[:7]}"


def _write_build_info(version: str, commit: str) -> None:
    """Emit omni/ui/_build_info.py so the installed package exposes
    __version__ and __commit__ at import time. Regenerated on every setup.py
    invocation; the file is gitignored."""
    BUILD_INFO_PATH.parent.mkdir(parents=True, exist_ok=True)
    BUILD_INFO_PATH.write_text(
        "# Auto-generated by ovui/setup.py — do not edit. Gitignored.\n"
        f"__version__ = {version!r}\n"
        f"__commit__ = {commit!r}\n",
        encoding="utf-8",
    )


_PROJECT_VERSION = _read_project_version()
_PROJECT_COMMIT = _read_commit_sha()
_QUALIFIED_VERSION = _qualified_version(_PROJECT_VERSION, _PROJECT_COMMIT)
_write_build_info(_QUALIFIED_VERSION, _PROJECT_COMMIT)


def _executable_name(name: str) -> str:
    return f"{name}.exe" if IS_WINDOWS else name


def _find_tool(name: str, env_var: Optional[str] = None) -> str:
    """Find a build tool without requiring the venv to be activated."""
    if env_var and os.environ.get(env_var):
        return os.environ[env_var]

    candidates = [
        Path(sys.executable).resolve().parent / _executable_name(name),
        Path(sys.prefix).resolve() / ("Scripts" if IS_WINDOWS else "bin") / _executable_name(name),
    ]
    for candidate in candidates:
        if candidate.is_file():
            return str(candidate)

    found = shutil.which(name)
    if found:
        return found

    raise RuntimeError(
        f"{name} is required to build ovui but was not found. "
        f"Install it into this Python environment, for example: "
        f"{sys.executable} -m pip install {name}"
    )


def _windows_fetchcontent_source_args(source_dir: Path, build_dir: Path) -> list:
    """Use local FetchContent source trees on Windows when they are already present.

    Windows development builds are commonly run in locked-down environments where
    CMake cannot clone GitHub dependencies during `pip install`. If a repo-level
    or package-level FetchContent cache already contains the source directories,
    pass them explicitly so `pip install -e ovui` works without shell setup.
    """
    if not IS_WINDOWS:
        return []

    deps_roots = [
        build_dir / "_deps",
        source_dir / "build" / "pip" / "_deps",
        source_dir.parent / "build" / "pip" / "_deps",
    ]
    deps = {
        "FREETYPE": "freetype-src",
        "GLFW": "glfw-src",
    }

    args = []
    for cmake_name, dirname in deps.items():
        for root in deps_roots:
            candidate = root / dirname
            if candidate.is_dir():
                args.append(f"-DFETCHCONTENT_SOURCE_DIR_{cmake_name}={candidate.as_posix()}")
                break
    return args


class CMakeExtension(Extension):
    """A setuptools Extension that delegates to CMake."""

    def __init__(self, name: str):
        super().__init__(name, sources=[])


def _find_artifact(build_dir: Path, subdir: str, filename: str) -> "Path | None":
    """Search for a build artifact in common output locations.

    Multi-config generators (Visual Studio) put binaries in a config subdir.
    """
    candidates = [
        build_dir / subdir / filename,
        build_dir / subdir / "Release" / filename,
        build_dir / subdir / "RelWithDebInfo" / filename,
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


class CMakeBuild(build_ext):
    """Custom build_ext that runs cmake to produce the shared libraries."""

    def build_extension(self, ext: Extension) -> None:
        # Directories
        source_dir = Path(__file__).resolve().parent
        build_dir = source_dir / "build" / "pip"
        build_dir.mkdir(parents=True, exist_ok=True)

        # Where setuptools wants the final package tree
        ext_fullpath = Path(self.get_ext_fullpath(ext.name)).resolve()
        pkg_dir = ext_fullpath.parent  # .../omni/ui/

        # ---- CMake configure ----
        cmake = _find_tool("cmake", "CMAKE_COMMAND")
        cmake_args = [
            "-DCMAKE_BUILD_TYPE=Release",
            f"-DPYTHON_EXECUTABLE={sys.executable}",
        ]
        cmake_args.extend(_windows_fetchcontent_source_args(source_dir, build_dir))

        # Forward Vulkan hints from environment if available
        vulkan_include = os.environ.get("Vulkan_INCLUDE_DIR", "")
        vulkan_library = os.environ.get("Vulkan_LIBRARY", "")
        if vulkan_include:
            cmake_args.append(f"-DVulkan_INCLUDE_DIR={vulkan_include}")
        if vulkan_library:
            cmake_args.append(f"-DVulkan_LIBRARY={vulkan_library}")

        # RPATH: $ORIGIN on Linux, @loader_path on macOS
        if IS_MACOS:
            cmake_args.extend([
                "-DCMAKE_INSTALL_RPATH=@loader_path",
                "-DCMAKE_BUILD_RPATH=@loader_path",
            ])
        elif not IS_WINDOWS:
            cmake_args.extend([
                "-DCMAKE_INSTALL_RPATH=$ORIGIN",
                "-DCMAKE_BUILD_RPATH=$ORIGIN",
            ])

        # Try to locate pybind11 cmake dir
        try:
            import pybind11
            cmake_args.append(f"-Dpybind11_DIR={pybind11.get_cmake_dir()}")
        except (ImportError, AttributeError):
            pass

        extra_cmake_args = shlex.split(os.environ.get("OMNIUI_CMAKE_ARGS", ""))
        if extra_cmake_args:
            cmake_args.extend(extra_cmake_args)

        subprocess.check_call(
            [cmake, str(source_dir)] + cmake_args,
            cwd=str(build_dir),
        )

        # ---- CMake build ----
        default_build_jobs = "1" if IS_WINDOWS else str(os.cpu_count() or 1)
        build_jobs = os.environ.get("OMNIUI_BUILD_JOBS", default_build_jobs)
        build_args = [
            "--build", str(build_dir),
            "--parallel", build_jobs,
            "--config", "Release",
        ]
        subprocess.check_call([cmake] + build_args)

        # ---- Copy artifacts into the package directory ----
        pkg_dir.mkdir(parents=True, exist_ok=True)

        ext_suffix = sysconfig.get_config_var("EXT_SUFFIX")
        if not ext_suffix:
            ext_suffix = ".pyd" if IS_WINDOWS else ".so"

        # Platform-specific library names
        if IS_WINDOWS:
            core_lib = "ovui.dll"
            standalone_lib = "omniui_standalone.dll"
        elif IS_MACOS:
            core_lib = "libovui.dylib"
            standalone_lib = "libomniui_standalone.dylib"
        else:
            core_lib = "libovui.so"
            standalone_lib = "libomniui_standalone.so"

        # Locate and copy the pybind11 module
        pybind_src = _find_artifact(build_dir, "bindings", f"_ui{ext_suffix}")
        if pybind_src:
            shutil.copy2(str(pybind_src), str(pkg_dir / f"_ui{ext_suffix}"))
            print(f"  copied {pybind_src.name} -> {pkg_dir / f'_ui{ext_suffix}'}")

        # Locate and copy the core shared library
        core_src = _find_artifact(build_dir, "core", core_lib)
        if core_src:
            shutil.copy2(str(core_src), str(pkg_dir / core_lib))
            print(f"  copied {core_src.name} -> {pkg_dir / core_lib}")

        # Locate and copy the standalone shared library
        standalone_src = _find_artifact(build_dir, "standalone", standalone_lib)
        if standalone_src:
            shutil.copy2(str(standalone_src), str(pkg_dir / standalone_lib))
            print(f"  copied {standalone_src.name} -> {pkg_dir / standalone_lib}")

        # Also copy versioned shared lib files (Linux: .so.X.Y.Z, macOS: .X.Y.Z.dylib)
        if not IS_WINDOWS:
            for lib_name in ["libovui", "libomniui_standalone"]:
                lib_dir = build_dir / ("core" if "ovui" in lib_name else "standalone")
                if IS_MACOS:
                    patterns = [f"{lib_name}.*.dylib"]
                else:
                    patterns = [f"{lib_name}.so.*"]
                for pattern in patterns:
                    for f in sorted(lib_dir.glob(pattern)):
                        target = pkg_dir / f.name
                        # Always overwrite: the pkg_dir may persist across builds
                        # (setuptools reuses build/lib.*/ between pip invocations),
                        # so a stale existence check would keep old binaries.
                        shutil.copy2(str(f), str(target))
                        print(f"  copied {f.name} -> {target}")

        # ---- Copy resource files ----
        resources_src = source_dir / "resources"
        resources_dst = pkg_dir / "resources"

        if resources_src.exists():
            # Fonts
            fonts_src = resources_src / "fonts"
            fonts_dst = resources_dst / "fonts"
            if fonts_src.exists():
                fonts_dst.mkdir(parents=True, exist_ok=True)
                # Clear stale font/license files from previous builds so files
                # removed from the source tree (e.g. NVIDIASans_*) don't linger
                # in editable installs — setuptools reuses build/lib.*/ across
                # pip invocations.
                for pattern in ("*.ttf", "*.txt", "*.md"):
                    for stale in fonts_dst.glob(pattern):
                        stale.unlink()
                    for src in fonts_src.glob(pattern):
                        shutil.copy2(str(src), str(fonts_dst / src.name))
                        print(f"  copied font asset {src.name}")

            # Glyphs
            glyphs_src = resources_src / "glyphs"
            glyphs_dst = resources_dst / "glyphs"
            if glyphs_src.exists() and any(glyphs_src.iterdir()):
                glyphs_dst.mkdir(parents=True, exist_ok=True)
                for svg in glyphs_src.glob("*.svg"):
                    shutil.copy2(str(svg), str(glyphs_dst / svg.name))
                    print(f"  copied glyph {svg.name}")

            # Twemoji atlas
            atlas_png = resources_src / "twemoji-atlas.png"
            atlas_json = resources_src / "twemoji-atlas.json"
            if atlas_png.exists():
                resources_dst.mkdir(parents=True, exist_ok=True)
                shutil.copy2(str(atlas_png), str(resources_dst / atlas_png.name))
                print(f"  copied {atlas_png.name}")
            if atlas_json.exists():
                resources_dst.mkdir(parents=True, exist_ok=True)
                shutil.copy2(str(atlas_json), str(resources_dst / atlas_json.name))
                print(f"  copied {atlas_json.name}")

        # ---- Copy Python source files ----
        py_src = source_dir / "python" / "omni" / "ui"
        for py_file in py_src.glob("*.py"):
            target = pkg_dir / py_file.name
            if not target.exists():
                shutil.copy2(str(py_file), str(target))
                print(f"  copied {py_file.name}")

        # markdown_providers subpackage
        providers_src = py_src / "markdown_providers"
        providers_dst = pkg_dir / "markdown_providers"
        if providers_src.exists():
            providers_dst.mkdir(parents=True, exist_ok=True)
            for py_file in providers_src.glob("*.py"):
                target = providers_dst / py_file.name
                shutil.copy2(str(py_file), str(target))
                print(f"  copied markdown_providers/{py_file.name}")

        # THIRD_PARTY_NOTICES.md from the repo root, bundled inside omni.ui
        # so it ships with the wheel and matching package_data picks it up.
        notices_src = REPO_ROOT / "THIRD_PARTY_NOTICES.md"
        if notices_src.exists():
            shutil.copy2(str(notices_src), str(pkg_dir / notices_src.name))
            print(f"  copied {notices_src.name}")

        # ---- Copy omni.ui_scene artifacts ----
        # _scene.so and libovuiscene.so* go into a sibling omni/ui_scene/ dir.
        scene_pkg_dir = pkg_dir.parent / "ui_scene"
        scene_pkg_dir.mkdir(parents=True, exist_ok=True)

        if IS_WINDOWS:
            scene_lib = "ovuiscene.dll"
        elif IS_MACOS:
            scene_lib = "libovuiscene.dylib"
        else:
            scene_lib = "libovuiscene.so"

        # pybind11 scene module
        scene_pybind_src = _find_artifact(build_dir, "bindings", f"_scene{ext_suffix}")
        if scene_pybind_src:
            shutil.copy2(str(scene_pybind_src), str(scene_pkg_dir / f"_scene{ext_suffix}"))
            print(f"  copied {scene_pybind_src.name} -> {scene_pkg_dir / f'_scene{ext_suffix}'}")

        # scene shared library
        scene_lib_src = _find_artifact(build_dir, "core", scene_lib)
        if scene_lib_src:
            shutil.copy2(str(scene_lib_src), str(scene_pkg_dir / scene_lib))
            print(f"  copied {scene_lib_src.name} -> {scene_pkg_dir / scene_lib}")

        # versioned scene lib files
        if not IS_WINDOWS:
            scene_lib_dir = build_dir / "core"
            lib_base = "libovuiscene"
            patterns = [f"{lib_base}.*.dylib"] if IS_MACOS else [f"{lib_base}.so.*"]
            for pattern in patterns:
                for f in sorted(scene_lib_dir.glob(pattern)):
                    shutil.copy2(str(f), str(scene_pkg_dir / f.name))
                    print(f"  copied {f.name} -> {scene_pkg_dir / f.name}")

        # Python source files for the scene package
        scene_py_src = source_dir / "python" / "omni" / "ui_scene"
        for py_file in scene_py_src.glob("*.py"):
            target = scene_pkg_dir / py_file.name
            if not target.exists():
                shutil.copy2(str(py_file), str(target))
                print(f"  copied scene {py_file.name}")


# Ensure the omni namespace package exists
def _ensure_namespace_packages(pkg_dir: Path):
    """Create __init__.py for the 'omni' namespace package if needed."""
    omni_init = pkg_dir / "__init__.py"
    if not omni_init.exists():
        omni_init.parent.mkdir(parents=True, exist_ok=True)
        omni_init.write_text(
            "# Namespace package - see PEP 420\n"
            "from pkgutil import extend_path\n"
            "__path__ = extend_path(__path__, __name__)\n"
        )


setup(
    name="ovui",
    version=_QUALIFIED_VERSION,
    description="ovui — GPU-accelerated Python UI toolkit",
    ext_modules=[CMakeExtension("omni.ui._ui")],
    cmdclass={"build_ext": CMakeBuild},
    packages=["omni", "omni.ui", "omni.ui.markdown_providers", "omni.ui.standalone", "omni.ui_scene"],
    package_dir={
        "omni":                      "python/omni",
        "omni.ui":                   "python/omni/ui",
        "omni.ui.markdown_providers": "python/omni/ui/markdown_providers",
        "omni.ui.standalone":        "python/omni/ui/standalone",
        "omni.ui_scene":             "python/omni/ui_scene",
    },
    package_data={
        "omni.ui": [
            "*.so",
            "*.so.*",
            "*.dylib",
            "*.*.dylib",
            "*.dll",
            "*.pyd",
            "THIRD_PARTY_NOTICES.md",
            "resources/fonts/*.ttf",
            "resources/fonts/*.txt",
            "resources/fonts/*.md",
            "resources/glyphs/*.svg",
            "resources/twemoji-atlas.png",
            "resources/twemoji-atlas.json",
        ],
        "omni.ui_scene": [
            "*.so",
            "*.so.*",
            "*.dylib",
            "*.*.dylib",
            "*.dll",
            "*.pyd",
        ],
    },
    python_requires=">=3.8",
    zip_safe=False,
)
