"""
Enrich a CycloneDX SBOM generated by `conan cyclonedx` with:
  - Full license text fetched from upstream GitHub sources
  - CPE identifiers for vulnerability scanner matching (NVD/OSV)
  - Python deps from pyproject.toml (not covered by Conan)

Deps are fetched from the exact git refs pinned in CMakeLists.txt / conanfile.py;
no package download or conan install required.

Usage:
    python3 ovui/tools/sbom/enrich_sbom_licenses.py [--sbom sbom.cdx.json] [--out sbom.cdx.json]
"""
import argparse
import json
import os
import urllib.request
import urllib.error

GITHUB_RAW = "https://raw.githubusercontent.com"

# ---------------------------------------------------------------------------
# License text sources: conan name -> list of raw URLs to try in order.
# ---------------------------------------------------------------------------
LICENSE_SOURCES = {
    "freetype": [
        f"{GITHUB_RAW}/freetype/freetype/VER-2-13-2/docs/FTL.TXT",
        f"{GITHUB_RAW}/freetype/freetype/VER-2-13-2/LICENSE.TXT",
    ],
    "glfw": [
        f"{GITHUB_RAW}/glfw/glfw/3.4/LICENSE.md",
    ],
    "glad": [
        f"{GITHUB_RAW}/Dav1dde/glad/1ecd45775d96f35170458e6b148eb0708967e402/LICENSE",
    ],
    "glm": [
        f"{GITHUB_RAW}/g-truc/glm/bf71a834948186f4097caa076cd2663c69a10e1e/copying.txt",
    ],
    "boost": [
        f"{GITHUB_RAW}/boostorg/preprocessor/c4ea7e40d365ba28faecef8917d5c3f1e0121bf9/LICENSE_1_0.txt",
        f"{GITHUB_RAW}/boostorg/boost/boost-1.85.0/LICENSE_1_0.txt",
    ],
    "stb": [
        f"{GITHUB_RAW}/nothings/stb/31c1ad37456438565541f4919958214b6e762fb4/LICENSE",
    ],
    "md4c": [
        f"{GITHUB_RAW}/mity/md4c/729e6b8b320caa96328968ab27d7db2235e4fb47/LICENSE.md",
    ],
    "pybind11": [
        f"{GITHUB_RAW}/pybind/pybind11/v2.13.6/LICENSE",
    ],
    "opengl": [],  # virtual system package — no upstream source
}

# ---------------------------------------------------------------------------
# CPE overrides: conan name -> (vendor, product).
# Default convention when not listed: vendor == product == name.lower().
# Follows NVD CPE naming; see https://nvd.nist.gov/products/cpe/search
# ---------------------------------------------------------------------------
CPE_OVERRIDES = {
    "boost":    ("boost",    "boost"),
    "freetype": ("freetype", "freetype"),
    "glad":     ("glad_project", "glad"),
    "glfw":     ("glfw",     "glfw"),
    "glm":      ("g-truc",   "opengl_mathematics"),
    "md4c":     ("md4c_project", "md4c"),
    "opengl":   ("khronos",  "opengl"),
    "pybind11": ("pybind",   "pybind11"),
    "stb":      ("stb_project", "stb"),
    # Python build deps
    "cmake":       ("kitware",  "cmake"),
    "setuptools":  ("python",   "setuptools"),
    "wheel":       ("python",   "wheel"),
    "numpy":       ("numpy",    "numpy"),
}


def _cpe(name, version):
    vendor, product = CPE_OVERRIDES.get(name, (name.lower(), name.lower()))
    return f"cpe:2.3:a:{vendor}:{product}:{version}:*:*:*:*:*:*:*"


# ---------------------------------------------------------------------------
# Python deps from pyproject.toml — added as components with PyPI PURLs.
# Sourced from THIRD_PARTY_NOTICES.md section 6 (the authoritative list).
# ---------------------------------------------------------------------------
PYTHON_COMPONENTS = [
    # Build-system requires (pyproject.toml build-system.requires)
    {
        "type": "library",
        "bom-ref": "pkg:pypi/setuptools@68.0",
        "name": "setuptools",
        "version": "68.0",
        "purl": "pkg:pypi/setuptools@68.0",
        "licenses": [{"license": {"id": "MIT"}}],
        "properties": [{"name": "ovui:dep-type", "value": "build-system"}],
    },
    {
        "type": "library",
        "bom-ref": "pkg:pypi/wheel@0.47.0",
        "name": "wheel",
        "version": "0.47.0",
        "purl": "pkg:pypi/wheel@0.47.0",
        "licenses": [{"license": {"id": "MIT"}}],
        "properties": [{"name": "ovui:dep-type", "value": "build-system"}],
    },
    {
        "type": "library",
        "bom-ref": "pkg:pypi/cmake@3.22",
        "name": "cmake",
        "version": "3.22",
        "purl": "pkg:pypi/cmake@3.22",
        "licenses": [{"license": {"id": "Apache-2.0 OR BSD-3-Clause"}}],
        "properties": [{"name": "ovui:dep-type", "value": "build-system"}],
    },
    {
        "type": "library",
        "bom-ref": "pkg:pypi/pybind11@2.11",
        "name": "pybind11",
        "version": "2.11",
        "purl": "pkg:pypi/pybind11@2.11",
        "licenses": [{"license": {"id": "BSD-3-Clause"}}],
        "properties": [{"name": "ovui:dep-type", "value": "build-system"}],
    },
    # Optional runtime deps (pyproject.toml optional-dependencies.examples)
    {
        "type": "library",
        "bom-ref": "pkg:pypi/numpy@1.21",
        "name": "numpy",
        "version": "1.21",
        "purl": "pkg:pypi/numpy@1.21",
        "licenses": [{"license": {"id": "BSD-3-Clause"}}],
        "properties": [{"name": "ovui:dep-type", "value": "optional-examples"}],
    },
    {
        "type": "library",
        "bom-ref": "pkg:pypi/cuda-python",
        "name": "cuda-python",
        "version": "13.2.0",
        "purl": "pkg:pypi/cuda-python@13.2.0",
        "licenses": [{"license": {"id": "LicenseRef-NVIDIA-SOFTWARE-LICENSE"}}],
        "properties": [{"name": "ovui:dep-type", "value": "optional-examples"}],
    },
]

# ---------------------------------------------------------------------------
# Vendored deps: read license from the local tree.
# ---------------------------------------------------------------------------
_VENDORED = [
    {
        "type": "library",
        "bom-ref": "imgui/1.92.7",
        "name": "imgui",
        "version": "1.92.7",
        "purl": "pkg:github/ocornut/imgui@v1.92.7",
        "description": "Bloat-free Immediate Mode Graphical User Interface for C++",
        "licenses": [{"license": {"id": "MIT"}}],
        "cpe": _cpe("imgui", "1.92.7"),
        "externalReferences": [
            {"type": "website", "url": "https://github.com/ocornut/imgui"}
        ],
        "properties": [
            {"name": "ovui:vendored", "value": "true"},
            {"name": "ovui:path", "value": "ovui/third_party/imgui"},
        ],
    }
]


def _local_imgui_license():
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
    candidates = [
        os.path.join(repo_root, "ovui", "third_party", "imgui", "LICENSE.txt"),
        os.path.join(repo_root, "ovui", "third_party", "imgui", "LICENSE"),
    ]
    for path in candidates:
        if os.path.isfile(path):
            with open(path, encoding="utf-8", errors="ignore") as fh:
                return fh.read()
    try:
        return _fetch(f"{GITHUB_RAW}/ocornut/imgui/v1.92.7/LICENSE.txt")
    except Exception:
        return None


def _fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "sbom-enricher/1.0"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        return resp.read().decode("utf-8", errors="ignore")


def _fetch_license(name):
    if name == "imgui":
        return _local_imgui_license()
    urls = LICENSE_SOURCES.get(name, [])
    for url in urls:
        try:
            text = _fetch(url)
            if text and len(text) > 20:
                return text
        except urllib.error.HTTPError as e:
            if e.code != 404:
                print(f"  [warn] {name}: HTTP {e.code} for {url}")
        except Exception as e:
            print(f"  [warn] {name}: {e}")
    return None


def _embed_license_text(component, text):
    for lic_entry in component.get("licenses", []):
        if isinstance(lic_entry, dict) and "license" in lic_entry:
            lic_entry["license"]["text"] = {"contentType": "text/plain", "content": text}


def enrich(sbom_path, out_path):
    with open(sbom_path, encoding="utf-8") as fh:
        sbom = json.load(fh)

    components = sbom.get("components", [])

    # --- CPEs + license text for Conan-resolved components ---
    license_skipped = []
    for component in components:
        name = component.get("name", "")
        version = component.get("version", "")

        # Add CPE if not already present
        if not component.get("cpe"):
            component["cpe"] = _cpe(name, version)

        # Update purl to point at actual upstream source where possible
        if name == "glad":
            component["purl"] = f"pkg:github/Dav1dde/glad@1ecd45775d96f35170458e6b148eb0708967e402"
        elif name == "glm":
            component["purl"] = f"pkg:github/g-truc/glm@bf71a834948186f4097caa076cd2663c69a10e1e"
        elif name == "stb":
            component["purl"] = f"pkg:github/nothings/stb@31c1ad37456438565541f4919958214b6e762fb4"
        elif name == "md4c":
            component["purl"] = f"pkg:github/mity/md4c@729e6b8b320caa96328968ab27d7db2235e4fb47"
        elif name == "boost":
            component["purl"] = f"pkg:github/boostorg/preprocessor@c4ea7e40d365ba28faecef8917d5c3f1e0121bf9"

        if not component.get("licenses"):
            license_skipped.append(name)
            continue

        print(f"  {name}/{version} ...", end=" ", flush=True)
        text = _fetch_license(name)
        if text:
            _embed_license_text(component, text)
            print("ok")
        else:
            print("no source")
            license_skipped.append(name)

    # --- Vendored deps (imgui) ---
    for v in _VENDORED:
        text = _fetch_license(v["name"])
        if text:
            _embed_license_text(v, text)
        components.append(v)

    # --- Python deps ---
    for py_comp in PYTHON_COMPONENTS:
        if not py_comp.get("cpe"):
            py_comp["cpe"] = _cpe(py_comp["name"], py_comp["version"])
        components.append(py_comp)

    sbom["components"] = components

    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(sbom, fh, indent=2)

    enriched = sum(1 for c in components if any(
        "text" in l.get("license", {}) for l in c.get("licenses", [])
    ))
    print(f"\nComponents: {len(components)} total, {enriched} with license text")
    if license_skipped:
        print(f"License text skipped: {license_skipped}")
    print(f"Output: {out_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sbom", default="sbom.cdx.json")
    parser.add_argument("--out", default=None)
    args = parser.parse_args()
    enrich(args.sbom, args.out or args.sbom)


if __name__ == "__main__":
    main()
