# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

"""Provider-neutral UI data-adapter interfaces and shared helpers."""

from ovui_data_adapters.common._adapter_registry import (
    ADAPTER_ENTRY_POINT_GROUP,
    AdapterFactories,
    AdapterModuleLoadFailure,
    AdapterProvider,
    AdapterProviderNotFoundError,
    AdapterProviderSelectionError,
    AdapterRegistry,
    AdapterRegistryError,
    DuplicateAdapterProviderError,
    discover_adapter_modules,
    get_adapter_factories,
    select_adapter,
)
from ovui_data_adapters.common._bound_camera_pose import BoundCameraPose
from ovui_data_adapters.common._command import Command, CommandCancelled
from ovui_data_adapters.common._environment import omniui_headless_enabled
from ovui_data_adapters.common._gpu_frame import (
    _STANDALONE_NOOP_MARKER,
    GpuFrame,
    ZeroCopyState,
    _Mode,
)
from ovui_data_adapters.common._subscription import SubscriptionProtocol
from ovui_data_adapters.common._undo_manager import UndoManagerProtocol
from ovui_data_adapters.common.create_actions import (
    CREATE_ACTION_CATEGORY_ORDER,
    CreateActionCatalog,
    CreateActionCategory,
    CreateActionCategoryDescriptor,
    CreateActionDescriptor,
    CreateActionErrorCode,
    CreateActionRequirement,
    CreateActionWarning,
    CreateActionWarningSeverity,
    CreateActionsAdapter,
    CreateBindingPolicy,
    CreatePlacementPolicy,
    CreateRequest,
    CreateResult,
    CreateSelectionPolicy,
)
from ovui_data_adapters.common.core_materials import (
    BindMaterialRequest,
    BindMaterialResult,
    CoreMaterialBindingPolicy,
    CoreMaterialCatalog,
    CoreMaterialDescriptor,
    CoreMaterialErrorCode,
    CoreMaterialFamily,
    CoreMaterialGroupDescriptor,
    CoreMaterialKind,
    CoreMaterialRequirement,
    CoreMaterialWarning,
    CoreMaterialWarningSeverity,
    CoreMaterialsAdapter,
    CreateAndBindMaterialResult,
    CreateMaterialRequest,
    CreateMaterialResult,
)
from ovui_data_adapters.common.render_targets import (
    RenderTargetActivationResult,
    RenderTargetCatalog,
    RenderTargetDescriptor,
    RenderTargetKind,
    RenderTargetOutputKind,
    RenderTargetWarning,
    RenderTargetWarningSeverity,
)
from ovui_data_adapters.common.render_vars import (
    RenderVarCategoricalSettings,
    RenderVarHdrSettings,
    RenderVarOutputCatalog,
    RenderVarOutputDescriptor,
    RenderVarOutputFrame,
    RenderVarOutputKind,
    RenderVarOutputRequest,
    RenderVarOutputRequestResult,
    RenderVarPresetKind,
    RenderVarProbeRequest,
    RenderVarProbeResult,
    RenderVarScalarRangeSettings,
    RenderVarToneMap,
    RenderVarVectorSettings,
    RenderVarVisualizationPreset,
    RenderVarWarning,
    RenderVarWarningSeverity,
)
from ovui_data_adapters.common.render_settings import (
    RenderSettingApplyResult,
    RenderSettingDescriptor,
    RenderSettingRequirement,
    RenderSettingResetResult,
    RenderSettingValidationResult,
    RenderSettingValueConstraints,
    RenderSettingValueState,
    RenderSettingValueType,
    RenderSettingVisibility,
    RenderSettingWarning,
    RenderSettingWarningSeverity,
    RenderSettingsAdapter,
    RenderSettingsCatalog,
    RenderSettingsGroupDescriptor,
    RenderSettingsProviderDescriptor,
)
from ovui_data_adapters.common.viewport_state import (
    ViewportCameraState,
    ViewportStateAdapter,
    ViewportStateSnapshot,
    ViewportStreamState,
)
from ovui_data_adapters.common.point_cloud import (
    PointCloudChannelDescriptor,
    PointCloudChannelSemantic,
    PointCloudColorMode,
    PointCloudCoordinateSpace,
    PointCloudFrame,
    PointCloudOutputCatalog,
    PointCloudOutputDescriptor,
    PointCloudRequest,
    PointCloudRequestResult,
    PointCloudWarning,
    PointCloudWarningSeverity,
)
from ovui_data_adapters.common.adapters import (
    _DEFAULT_TYPE_CATEGORY_MAP,
    AABB,
    AdapterCapabilities,
    AdapterCapability,
    AdapterCapabilityStatus,
    AdapterItem,
    AttributeMetadata,
    BadgeFlags,
    BoundingBox,
    ChangeEvent,
    ChangeEventType,
    ContextManager,
    GpuFrameHandle,
    ImageProvider,
    ItemFlags,
    LayerEvent,
    LayerEventType,
    LayerHandle,
    LayerSnapshot,
    LayerStackCapabilities,
    LayerStackAdapter,
    Matrix4d,
    PrimSpecDescriptor,
    PrimSpecifier,
    PropertyCapabilities,
    PropertyAdapter,
    RendererAdapter,
    ReparentPosition,
    SelectionAdapter,
    StageAdapter,
    StageCapabilities,
    StageChoice,
    TransformEditMode,
    TransformEditPolicy,
    TransformAdapter,
    UnresolvedDeliveryDebtError,
    VIEWPORT_CAMERA_POSE_SOURCE,
    Vec3f,
    VisibilityState,
    is_camera_property_only_info_change,
    is_viewport_camera_pose_change_event,
)

__all__ = [
    # adapter registry
    "ADAPTER_ENTRY_POINT_GROUP",
    "AdapterFactories",
    "AdapterModuleLoadFailure",
    "AdapterProvider",
    "AdapterProviderNotFoundError",
    "AdapterProviderSelectionError",
    "AdapterRegistry",
    "AdapterRegistryError",
    "DuplicateAdapterProviderError",
    "discover_adapter_modules",
    "get_adapter_factories",
    "select_adapter",
    "omniui_headless_enabled",
    # adapter ABCs
    "LayerStackAdapter",
    "PropertyAdapter",
    "RendererAdapter",
    "CreateActionsAdapter",
    "CoreMaterialsAdapter",
    "RenderSettingsAdapter",
    "SelectionAdapter",
    "StageAdapter",
    "TransformAdapter",
    "ViewportStateAdapter",
    # enums / flags
    "AdapterCapabilityStatus",
    "BadgeFlags",
    "ChangeEventType",
    "CreateActionCategory",
    "CreateActionErrorCode",
    "CreateActionRequirement",
    "CreateActionWarningSeverity",
    "CreateBindingPolicy",
    "CreatePlacementPolicy",
    "CreateSelectionPolicy",
    "CoreMaterialBindingPolicy",
    "CoreMaterialErrorCode",
    "CoreMaterialFamily",
    "CoreMaterialKind",
    "CoreMaterialRequirement",
    "CoreMaterialWarningSeverity",
    "ItemFlags",
    "LayerEventType",
    "PrimSpecifier",
    "ReparentPosition",
    "PointCloudChannelSemantic",
    "PointCloudColorMode",
    "PointCloudCoordinateSpace",
    "PointCloudWarningSeverity",
    "RenderTargetKind",
    "RenderTargetOutputKind",
    "RenderTargetWarningSeverity",
    "RenderVarOutputKind",
    "RenderVarPresetKind",
    "RenderVarToneMap",
    "RenderVarWarningSeverity",
    "RenderSettingRequirement",
    "RenderSettingValueType",
    "RenderSettingVisibility",
    "RenderSettingWarningSeverity",
    "TransformEditMode",
    "VisibilityState",
    # dataclasses
    "AdapterCapabilities",
    "AdapterCapability",
    "AttributeMetadata",
    "BoundCameraPose",
    "ChangeEvent",
    "CreateActionCatalog",
    "CreateActionCategoryDescriptor",
    "CreateActionDescriptor",
    "CreateActionWarning",
    "CreateRequest",
    "CreateResult",
    "BindMaterialRequest",
    "BindMaterialResult",
    "CoreMaterialCatalog",
    "CoreMaterialDescriptor",
    "CoreMaterialGroupDescriptor",
    "CoreMaterialWarning",
    "CreateAndBindMaterialResult",
    "CreateMaterialRequest",
    "CreateMaterialResult",
    "LayerEvent",
    "LayerHandle",
    "LayerSnapshot",
    "LayerStackCapabilities",
    "PointCloudChannelDescriptor",
    "PointCloudFrame",
    "PointCloudOutputCatalog",
    "PointCloudOutputDescriptor",
    "PointCloudRequest",
    "PointCloudRequestResult",
    "PointCloudWarning",
    "PrimSpecDescriptor",
    "RenderTargetActivationResult",
    "RenderTargetCatalog",
    "RenderTargetDescriptor",
    "RenderTargetWarning",
    "RenderVarCategoricalSettings",
    "RenderVarHdrSettings",
    "RenderVarOutputCatalog",
    "RenderVarOutputDescriptor",
    "RenderVarOutputFrame",
    "RenderVarOutputRequest",
    "RenderVarOutputRequestResult",
    "RenderVarProbeRequest",
    "RenderVarProbeResult",
    "RenderVarScalarRangeSettings",
    "RenderVarVectorSettings",
    "RenderVarVisualizationPreset",
    "RenderVarWarning",
    "RenderSettingApplyResult",
    "RenderSettingDescriptor",
    "RenderSettingResetResult",
    "RenderSettingValidationResult",
    "RenderSettingValueConstraints",
    "RenderSettingValueState",
    "RenderSettingWarning",
    "RenderSettingsCatalog",
    "RenderSettingsGroupDescriptor",
    "RenderSettingsProviderDescriptor",
    "PropertyCapabilities",
    "StageCapabilities",
    "StageChoice",
    "TransformEditPolicy",
    "ViewportCameraState",
    "ViewportStateSnapshot",
    "ViewportStreamState",
    "VIEWPORT_CAMERA_POSE_SOURCE",
    "CREATE_ACTION_CATEGORY_ORDER",
    # opaque type aliases
    "AABB",
    "AdapterItem",
    "BoundingBox",
    "ContextManager",
    "GpuFrameHandle",
    "ImageProvider",
    "Matrix4d",
    "Vec3f",
    # protocols and command surface (Steps 2/3)
    "Command",
    "CommandCancelled",
    "SubscriptionProtocol",
    "UnresolvedDeliveryDebtError",
    "UndoManagerProtocol",
    # zero-copy / GPU frame surface (Step 4)
    "GpuFrame",
    "ZeroCopyState",
    "_Mode",
    "_STANDALONE_NOOP_MARKER",
    "is_camera_property_only_info_change",
    "is_viewport_camera_pose_change_event",
    # private lookup table — explicit so dotted access continues to work
    "_DEFAULT_TYPE_CATEGORY_MAP",
]
